// Simulated fax transmission — the step a participant still performs by hand
// once a form is filled. Nothing is dialed and nothing leaves this process: the
// "transmission" renders a cover sheet, staples it in front of the form, and
// records a receipt. It exists so the demo can show the manual rail the
// interoperability work is meant to delete.

import { PDFDocument } from "pdf-lib";
import { PdfWriter } from "@/lib/pdf/render";

export type FaxCoverInput = {
  senderName: string;
  destinationName: string;
  destinationFax: string;
  caseNumberLast4: string | null;
  programName: string | null;
  formName: string;
  formPageCount: number;
  confirmationNumber: string;
  sentAt: Date;
};

/**
 * Confirmation numbers imitate what a fax machine prints on its receipt: a
 * short, human-readable identifier a caseworker can be quoted over the phone.
 * Collisions are prevented by the unique column, not by this function.
 */
export function generateConfirmationNumber(): string {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no I/O/0/1 — these get read aloud
  let suffix = "";
  for (let i = 0; i < 6; i++) {
    suffix += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return `FX-${suffix}`;
}

function formatTimestamp(date: Date): string {
  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

async function renderCoverSheet(input: FaxCoverInput): Promise<Uint8Array> {
  const writer = await PdfWriter.create();

  writer.title("Fax cover sheet");
  writer.text(
    "SIMULATED TRANSMISSION — generated by SnappyForms for demonstration. No fax was dialed and no document was sent to any agency.",
    { size: 8, bold: true }
  );
  writer.spacer(10);

  writer.heading("Transmission");
  writer.keyValue("To", input.destinationName);
  writer.keyValue("Fax number", input.destinationFax);
  writer.keyValue("From", input.senderName);
  writer.keyValue("Date sent", formatTimestamp(input.sentAt));
  writer.keyValue("Confirmation", input.confirmationNumber);
  // The cover sheet counts itself — that is what the receiving office reconciles against.
  writer.keyValue("Pages", `${input.formPageCount + 1} (including this cover sheet)`);

  writer.spacer(6);
  writer.heading("Regarding");
  writer.keyValue("Document", input.formName);
  if (input.programName) writer.keyValue("Program", input.programName);
  // Full case numbers are encrypted at rest and never printed — a fax travels in the clear.
  writer.keyValue("Case number", input.caseNumberLast4 ? `XXXX-${input.caseNumberLast4}` : "Not provided");

  writer.spacer(10);
  writer.heading("Message");
  writer.text(
    `Attached is the ${input.formName} documenting activity hours confirmed by the listed ` +
      `organization. Each entry was verified in SnappyForms by an authorized representative ` +
      `of that organization at the time of the activity. Please associate this submission ` +
      `with the case referenced above.`
  );

  writer.spacer(10);
  writer.text(
    "If any page is illegible, please contact the sender rather than the verifying organization.",
    { size: 9, gray: true }
  );

  return writer.bytes();
}

/**
 * The artifact that "went over the wire": cover sheet followed by the form
 * itself, so the demo can open exactly what a caseworker would receive.
 */
export async function renderFaxBundle(
  formPdf: Uint8Array,
  input: Omit<FaxCoverInput, "formPageCount">
): Promise<{ pdfBytes: Uint8Array; pageCount: number }> {
  const formDoc = await PDFDocument.load(formPdf);
  const formPageCount = formDoc.getPageCount();

  const coverPdf = await renderCoverSheet({ ...input, formPageCount });

  const bundle = await PDFDocument.create();
  const coverDoc = await PDFDocument.load(coverPdf);

  for (const page of await bundle.copyPages(coverDoc, coverDoc.getPageIndices())) {
    bundle.addPage(page);
  }
  for (const page of await bundle.copyPages(formDoc, formDoc.getPageIndices())) {
    bundle.addPage(page);
  }

  return { pdfBytes: await bundle.save(), pageCount: bundle.getPageCount() };
}
